# Generated by Django 6.0.3 on 2026-03-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhistory',
            name='event',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date', '-first_seen'], 'verbose_name': 'Tadbir', 'verbose_name_plural': 'Tadbirlar'},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_city_id_bea4e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_is_acti_ccac25_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitorlog',
            name='status',
            field=models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('error', 'Xatolik')], max_length=20),
        ),
        migrations.DeleteModel(
            name='EventHistory',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at_api',
        ),
        migrations.RemoveField(
            model_name='event',
            name='currency',
        ),
    ]
