# Generated by Django 6.0.3 on 2026-03-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_end_time_display_event_event_url_event_is_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interested_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='share_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
