# Generated by Django 6.0.3 on 2026-03-21 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_interested_count_event_share_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RACOArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'RA.CO Artist',
                'verbose_name_plural': 'RA.CO Artists',
            },
        ),
        migrations.CreateModel(
            name='RACOSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('cookies', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'RA.CO Session',
                'verbose_name_plural': 'RA.CO Sessions',
            },
        ),
        migrations.CreateModel(
            name='RACOVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RA.CO Venue',
                'verbose_name_plural': 'RA.CO Venues',
            },
        ),
        migrations.CreateModel(
            name='RACOEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('listing_date', models.DateTimeField(blank=True, null=True)),
                ('flyer_front', models.URLField(blank=True, null=True)),
                ('is_ticketed', models.BooleanField(default=False)),
                ('interested_count', models.IntegerField(default=0)),
                ('event_url', models.URLField(blank=True, null=True)),
                ('is_notified', models.BooleanField(db_index=True, default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('artists', models.ManyToManyField(blank=True, related_name='events', to='events.racoartist')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.racovenue')),
            ],
            options={
                'verbose_name': 'RA.CO Event',
                'verbose_name_plural': 'RA.CO Events',
                'ordering': ['-date', '-start_time', '-first_seen'],
            },
        ),
    ]
