# Generated by Django 6.0.3 on 2026-03-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_racoartist_racosession_racovenue_racoevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date', '-first_seen'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='monitorlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог мониторинга', 'verbose_name_plural': 'Логи мониторинга'},
        ),
        migrations.AlterModelOptions(
            name='racoartist',
            options={'verbose_name': 'Артист RA.CO', 'verbose_name_plural': 'Артисты RA.CO'},
        ),
        migrations.AlterModelOptions(
            name='racoevent',
            options={'ordering': ['-date', '-start_time', '-first_seen'], 'verbose_name': 'Событие RA.CO', 'verbose_name_plural': 'События RA.CO'},
        ),
        migrations.AlterModelOptions(
            name='racosession',
            options={'verbose_name': 'Сессия RA.CO', 'verbose_name_plural': 'Сессии RA.CO'},
        ),
        migrations.AlterModelOptions(
            name='racovenue',
            options={'verbose_name': 'Площадка RA.CO', 'verbose_name_plural': 'Площадки RA.CO'},
        ),
        migrations.AlterField(
            model_name='monitorlog',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка')], max_length=20),
        ),
    ]
